- databases:
  - name: til
    databaseName: til_production
    user: til

services:
  - type: web
    name: til
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: til
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
